<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // Platform group
            [
                'key' => 'platform.site_name',
                'value' => 'ATL Ticket Exchange',
                'type' => 'string',
                'group' => 'platform',
                'label' => 'Site Name',
                'description' => 'The name of the site shown in the nav and emails.',
                'is_public' => true,
            ],
            [
                'key' => 'platform.site_url',
                'value' => 'https://atlticket.exchange',
                'type' => 'string',
                'group' => 'platform',
                'label' => 'Site URL',
                'description' => 'The canonical URL of the site.',
                'is_public' => true,
            ],
            [
                'key' => 'platform.tagline',
                'value' => 'Atlanta\'s Peer-to-Peer Ticket Marketplace',
                'type' => 'string',
                'group' => 'platform',
                'label' => 'Site Tagline',
                'description' => 'Short tagline shown in hero and metadata.',
                'is_public' => true,
            ],
            [
                'key' => 'platform.maintenance_mode',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'platform',
                'label' => 'Maintenance Mode',
                'description' => 'When enabled, non-admin users see the maintenance page.',
                'is_public' => false,
            ],
            [
                'key' => 'platform.max_free_listings',
                'value' => '1',
                'type' => 'integer',
                'group' => 'platform',
                'label' => 'Max Free Tier Active Listings',
                'description' => 'Max concurrent active listings for free tier users.',
                'is_public' => false,
            ],
            [
                'key' => 'platform.max_member_saved_searches',
                'value' => '5',
                'type' => 'integer',
                'group' => 'platform',
                'label' => 'Max Member Tier Saved Searches',
                'description' => 'Max active saved searches for member tier users.',
                'is_public' => false,
            ],
            [
                'key' => 'platform.max_free_saved_searches',
                'value' => '1',
                'type' => 'integer',
                'group' => 'platform',
                'label' => 'Max Free Tier Saved Searches',
                'description' => 'Max active saved searches for free tier users.',
                'is_public' => false,
            ],
            [
                'key' => 'platform.listing_expiry_days',
                'value' => '30',
                'type' => 'integer',
                'group' => 'platform',
                'label' => 'Default Listing Expiry Days',
                'description' => 'Number of days a listing is active before expiring.',
                'is_public' => false,
            ],
            [
                'key' => 'platform.probation_threshold',
                'value' => '3',
                'type' => 'integer',
                'group' => 'platform',
                'label' => 'Probation Release Threshold',
                'description' => 'Number of approved listings before probation is lifted.',
                'is_public' => false,
            ],
            [
                'key' => 'platform.referral_credits',
                'value' => '2',
                'type' => 'integer',
                'group' => 'platform',
                'label' => 'Referral Credits Reward',
                'description' => 'Credits granted when a referred user converts.',
                'is_public' => false,
            ],
            [
                'key' => 'platform.featured_credits_per_hour',
                'value' => '1',
                'type' => 'integer',
                'group' => 'platform',
                'label' => 'Credits per Featured Hour',
                'description' => 'Credits required per hour of featured placement.',
                'is_public' => false,
            ],
            [
                'key' => 'platform.saved_search_alert_cooldown_hours',
                'value' => '24',
                'type' => 'integer',
                'group' => 'platform',
                'label' => 'Saved Search Alert Cooldown (hours)',
                'description' => 'Hours to wait before alerting the same user for the same search.',
                'is_public' => false,
            ],
            [
                'key' => 'platform.feedback_window_days',
                'value' => '30',
                'type' => 'integer',
                'group' => 'platform',
                'label' => 'Feedback Window Days',
                'description' => 'Days after a FeedbackRequest is created that users can leave feedback.',
                'is_public' => false,
            ],

            // Mail group
            [
                'key' => 'mail.driver',
                'value' => 'smtp',
                'type' => 'string',
                'group' => 'mail',
                'label' => 'Mail Driver',
                'description' => 'The mail transport driver.',
                'is_public' => false,
            ],
            [
                'key' => 'mail.from_address',
                'value' => 'noreply@atlticket.exchange',
                'type' => 'string',
                'group' => 'mail',
                'label' => 'From Address',
                'description' => 'Default from address for outgoing emails.',
                'is_public' => false,
            ],
            [
                'key' => 'mail.from_name',
                'value' => 'ATL Ticket Exchange',
                'type' => 'string',
                'group' => 'mail',
                'label' => 'From Name',
                'description' => 'Default from name for outgoing emails.',
                'is_public' => false,
            ],
            [
                'key' => 'mail.smtp_host',
                'value' => '',
                'type' => 'string',
                'group' => 'mail',
                'label' => 'SMTP Host',
                'description' => 'SMTP server hostname.',
                'is_public' => false,
            ],
            [
                'key' => 'mail.smtp_port',
                'value' => '587',
                'type' => 'integer',
                'group' => 'mail',
                'label' => 'SMTP Port',
                'description' => 'SMTP server port.',
                'is_public' => false,
            ],
            [
                'key' => 'mail.smtp_username',
                'value' => '',
                'type' => 'string',
                'group' => 'mail',
                'label' => 'SMTP Username',
                'description' => 'SMTP auth username.',
                'is_public' => false,
            ],
            [
                'key' => 'mail.smtp_password',
                'value' => '',
                'type' => 'string',
                'group' => 'mail',
                'label' => 'SMTP Password',
                'description' => 'SMTP auth password (stored encrypted).',
                'is_public' => false,
            ],

            // Stripe group
            [
                'key' => 'stripe.publishable_key',
                'value' => '',
                'type' => 'string',
                'group' => 'stripe',
                'label' => 'Stripe Publishable Key',
                'description' => 'Stripe publishable API key.',
                'is_public' => true,
            ],
            [
                'key' => 'stripe.secret_key',
                'value' => '',
                'type' => 'string',
                'group' => 'stripe',
                'label' => 'Stripe Secret Key',
                'description' => 'Stripe secret API key (stored encrypted).',
                'is_public' => false,
            ],
            [
                'key' => 'stripe.webhook_secret',
                'value' => '',
                'type' => 'string',
                'group' => 'stripe',
                'label' => 'Stripe Webhook Secret',
                'description' => 'Stripe webhook signing secret (stored encrypted).',
                'is_public' => false,
            ],
            [
                'key' => 'stripe.member_price_id',
                'value' => '',
                'type' => 'string',
                'group' => 'stripe',
                'label' => 'Member Tier Stripe Price ID',
                'description' => 'Stripe Price ID for the Member subscription tier.',
                'is_public' => false,
            ],
            [
                'key' => 'stripe.pro_price_id',
                'value' => '',
                'type' => 'string',
                'group' => 'stripe',
                'label' => 'Pro Tier Stripe Price ID',
                'description' => 'Stripe Price ID for the Pro subscription tier.',
                'is_public' => false,
            ],

            // SeatGeek group
            [
                'key' => 'seatgeek.client_id',
                'value' => '',
                'type' => 'string',
                'group' => 'seatgeek',
                'label' => 'SeatGeek Client ID',
                'description' => 'SeatGeek API client ID.',
                'is_public' => false,
            ],
            [
                'key' => 'seatgeek.client_secret',
                'value' => '',
                'type' => 'string',
                'group' => 'seatgeek',
                'label' => 'SeatGeek Client Secret',
                'description' => 'SeatGeek API client secret (stored encrypted).',
                'is_public' => false,
            ],
            [
                'key' => 'seatgeek.sync_enabled',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'seatgeek',
                'label' => 'SeatGeek Sync Enabled',
                'description' => 'Enable or disable automatic event syncing from SeatGeek.',
                'is_public' => false,
            ],
            [
                'key' => 'seatgeek.event_expire_days',
                'value' => '1',
                'type' => 'integer',
                'group' => 'seatgeek',
                'label' => 'Event Expire Days',
                'description' => 'Days after event_date to expire the event.',
                'is_public' => false,
            ],

            // SMS group
            [
                'key' => 'sms.active',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'sms',
                'label' => 'SMS Active',
                'description' => 'Enable or disable SMS notifications.',
                'is_public' => false,
            ],
            [
                'key' => 'sms.twilio_sid',
                'value' => '',
                'type' => 'string',
                'group' => 'sms',
                'label' => 'Twilio SID',
                'description' => 'Twilio Account SID.',
                'is_public' => false,
            ],
            [
                'key' => 'sms.twilio_auth_token',
                'value' => '',
                'type' => 'string',
                'group' => 'sms',
                'label' => 'Twilio Auth Token',
                'description' => 'Twilio Auth Token (stored encrypted).',
                'is_public' => false,
            ],
            [
                'key' => 'sms.twilio_from_number',
                'value' => '',
                'type' => 'string',
                'group' => 'sms',
                'label' => 'Twilio From Number',
                'description' => 'Twilio sending phone number.',
                'is_public' => false,
            ],

            // Features group
            [
                'key' => 'features.social_push_enabled',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'features',
                'label' => 'Social Push Enabled',
                'description' => 'Enable or disable social push for listings.',
                'is_public' => false,
            ],
            [
                'key' => 'features.giveaways_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'features',
                'label' => 'Giveaways Enabled',
                'description' => 'Enable or disable the giveaways feature.',
                'is_public' => false,
            ],
            [
                'key' => 'features.referrals_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'features',
                'label' => 'Referrals Enabled',
                'description' => 'Enable or disable the referral program.',
                'is_public' => false,
            ],
            [
                'key' => 'features.credits_enabled',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'features',
                'label' => 'Credits Enabled',
                'description' => 'Enable or disable the credits system.',
                'is_public' => false,
            ],

            // Affiliate group
            [
                'key' => 'affiliate.default_url',
                'value' => '',
                'type' => 'string',
                'group' => 'affiliate',
                'label' => 'Default Affiliate URL',
                'description' => 'Default affiliate URL appended to listings.',
                'is_public' => false,
            ],
            [
                'key' => 'affiliate.default_label',
                'value' => 'Buy on SeatGeek',
                'type' => 'string',
                'group' => 'affiliate',
                'label' => 'Default Affiliate Label',
                'description' => 'Default label for affiliate links.',
                'is_public' => false,
            ],

            // Social group
            [
                'key' => 'social.facebook_page_id',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'Facebook Page ID',
                'description' => 'Facebook Page ID for social push.',
                'is_public' => false,
            ],
            [
                'key' => 'social.facebook_page_access_token',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'Facebook Page Access Token',
                'description' => 'Facebook Page access token (stored encrypted).',
                'is_public' => false,
            ],
            [
                'key' => 'social.twitter_api_key',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'Twitter API Key',
                'description' => 'Twitter/X API key.',
                'is_public' => false,
            ],
            [
                'key' => 'social.twitter_api_secret',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'Twitter API Secret',
                'description' => 'Twitter/X API secret (stored encrypted).',
                'is_public' => false,
            ],
            [
                'key' => 'social.twitter_access_token',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'Twitter Access Token',
                'description' => 'Twitter/X access token.',
                'is_public' => false,
            ],
            [
                'key' => 'social.twitter_access_token_secret',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'Twitter Access Token Secret',
                'description' => 'Twitter/X access token secret (stored encrypted).',
                'is_public' => false,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
